component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/quartz/.*
- ./bin/org/quartz/core/.*
- ./bin/org/quartz/core/jmx/.*
- ./bin/org/quartz/ee/.*
- ./bin/org/quartz/ee/jmx/.*
- ./bin/org/quartz/ee/jmx/jboss/.*
- ./bin/org/quartz/ee/jmx/jboss/doc-files/.*
- ./bin/org/quartz/ee/jta/.*
- ./bin/org/quartz/ee/servlet/.*
- ./bin/org/quartz/examples/.*
- ./bin/org/quartz/examples/example1/.*
- ./bin/org/quartz/examples/example10/.*
- ./bin/org/quartz/examples/example11/.*
- ./bin/org/quartz/examples/example12/.*
- ./bin/org/quartz/examples/example13/.*
- ./bin/org/quartz/examples/example14/.*
- ./bin/org/quartz/examples/example15/.*
- ./bin/org/quartz/examples/example2/.*
- ./bin/org/quartz/examples/example3/.*
- ./bin/org/quartz/examples/example4/.*
- ./bin/org/quartz/examples/example5/.*
- ./bin/org/quartz/examples/example6/.*
- ./bin/org/quartz/examples/example7/.*
- ./bin/org/quartz/examples/example8/.*
- ./bin/org/quartz/examples/example9/.*
- ./bin/org/quartz/helpers/.*
- ./bin/org/quartz/impl/.*
- ./bin/org/quartz/impl/calendar/.*
- ./bin/org/quartz/impl/jdbcjobstore/.*
- ./bin/org/quartz/impl/jdbcjobstore/oracle/.*
- ./bin/org/quartz/impl/jdbcjobstore/oracle/weblogic/.*
- ./bin/org/quartz/jobs/.*
- ./bin/org/quartz/jobs/ee/.*
- ./bin/org/quartz/jobs/ee/ejb/.*
- ./bin/org/quartz/jobs/ee/jms/.*
- ./bin/org/quartz/jobs/ee/jmx/.*
- ./bin/org/quartz/jobs/ee/mail/.*
- ./bin/org/quartz/listeners/.*
- ./bin/org/quartz/plugins/.*
- ./bin/org/quartz/plugins/history/.*
- ./bin/org/quartz/plugins/management/.*
- ./bin/org/quartz/plugins/xml/.*
- ./bin/org/quartz/simpl/.*
- ./bin/org/quartz/spi/.*
- ./bin/org/quartz/utils/.*
- ./bin/org/quartz/utils/counter/.*
- ./bin/org/quartz/utils/counter/sampled/.*
- ./bin/org/quartz/utils/weblogic/.*
- ./bin/org/quartz/xml/.*
- ./docs/.*
- ./docs/api/.*
- ./docs/api/org/.*
- ./docs/api/org/quartz/.*
- ./docs/api/org/quartz/class-use/.*
- ./docs/api/org/quartz/core/.*
- ./docs/api/org/quartz/core/class-use/.*
- ./docs/api/org/quartz/core/jmx/.*
- ./docs/api/org/quartz/core/jmx/class-use/.*
- ./docs/api/org/quartz/ee/.*
- ./docs/api/org/quartz/ee/jmx/.*
- ./docs/api/org/quartz/ee/jmx/jboss/.*
- ./docs/api/org/quartz/ee/jmx/jboss/class-use/.*
- ./docs/api/org/quartz/ee/jmx/jboss/doc-files/.*
- ./docs/api/org/quartz/ee/jta/.*
- ./docs/api/org/quartz/ee/jta/class-use/.*
- ./docs/api/org/quartz/ee/servlet/.*
- ./docs/api/org/quartz/ee/servlet/class-use/.*
- ./docs/api/org/quartz/helpers/.*
- ./docs/api/org/quartz/helpers/class-use/.*
- ./docs/api/org/quartz/impl/.*
- ./docs/api/org/quartz/impl/calendar/.*
- ./docs/api/org/quartz/impl/calendar/class-use/.*
- ./docs/api/org/quartz/impl/class-use/.*
- ./docs/api/org/quartz/impl/jdbcjobstore/.*
- ./docs/api/org/quartz/impl/jdbcjobstore/class-use/.*
- ./docs/api/org/quartz/impl/jdbcjobstore/oracle/.*
- ./docs/api/org/quartz/impl/jdbcjobstore/oracle/class-use/.*
- ./docs/api/org/quartz/impl/jdbcjobstore/oracle/weblogic/.*
- ./docs/api/org/quartz/impl/jdbcjobstore/oracle/weblogic/class-use/.*
- ./docs/api/org/quartz/jobs/.*
- ./docs/api/org/quartz/jobs/class-use/.*
- ./docs/api/org/quartz/jobs/ee/.*
- ./docs/api/org/quartz/jobs/ee/ejb/.*
- ./docs/api/org/quartz/jobs/ee/ejb/class-use/.*
- ./docs/api/org/quartz/jobs/ee/jms/.*
- ./docs/api/org/quartz/jobs/ee/jms/class-use/.*
- ./docs/api/org/quartz/jobs/ee/jmx/.*
- ./docs/api/org/quartz/jobs/ee/jmx/class-use/.*
- ./docs/api/org/quartz/jobs/ee/mail/.*
- ./docs/api/org/quartz/jobs/ee/mail/class-use/.*
- ./docs/api/org/quartz/listeners/.*
- ./docs/api/org/quartz/listeners/class-use/.*
- ./docs/api/org/quartz/plugins/.*
- ./docs/api/org/quartz/plugins/class-use/.*
- ./docs/api/org/quartz/plugins/history/.*
- ./docs/api/org/quartz/plugins/history/class-use/.*
- ./docs/api/org/quartz/plugins/management/.*
- ./docs/api/org/quartz/plugins/management/class-use/.*
- ./docs/api/org/quartz/plugins/xml/.*
- ./docs/api/org/quartz/plugins/xml/class-use/.*
- ./docs/api/org/quartz/simpl/.*
- ./docs/api/org/quartz/simpl/class-use/.*
- ./docs/api/org/quartz/spi/.*
- ./docs/api/org/quartz/spi/class-use/.*
- ./docs/api/org/quartz/utils/.*
- ./docs/api/org/quartz/utils/class-use/.*
- ./docs/api/org/quartz/utils/counter/.*
- ./docs/api/org/quartz/utils/counter/class-use/.*
- ./docs/api/org/quartz/utils/counter/sampled/.*
- ./docs/api/org/quartz/utils/counter/sampled/class-use/.*
- ./docs/api/org/quartz/utils/weblogic/.*
- ./docs/api/org/quartz/utils/weblogic/class-use/.*
- ./docs/api/org/quartz/xml/.*
- ./docs/api/org/quartz/xml/class-use/.*
- ./docs/dbTables/.*
- ./docs/images/.*
- ./examples/.*
- ./examples/bin/.*
- ./examples/example1/.*
- ./examples/example10/.*
- ./examples/example11/.*
- ./examples/example12/.*
- ./examples/example13/.*
- ./examples/example14/.*
- ./examples/example15/.*
- ./examples/example2/.*
- ./examples/example3/.*
- ./examples/example4/.*
- ./examples/example5/.*
- ./examples/example6/.*
- ./examples/example7/.*
- ./examples/example8/.*
- ./examples/example9/.*
- ./lib/.*
- ./quartz/.*
- ./quartz-all/.*
- ./quartz-jboss/.*
- ./quartz-oracle/.*
- ./quartz-weblogic/.*
